import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'id' | 'ms' | 'zh' | 'ar' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tArray: (key: string) => string[];
  isTransitioning: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const setLanguage = (lang: Language) => {
    if (lang === language) return;
    
    // Start transition animation
    setIsTransitioning(true);
    document.body.classList.add('language-transitioning');
    
    setTimeout(() => {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
      // Update document direction for RTL languages
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      
      // End transition animation
      setTimeout(() => {
        setIsTransitioning(false);
        document.body.classList.remove('language-transitioning');
      }, 300);
    }, 150);
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const getTranslationValue = (key: string): any => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        // Fallback to English
        value = translations['en'];
        for (const fallbackKey of keys) {
          if (value && typeof value === 'object' && fallbackKey in value) {
            value = value[fallbackKey];
          } else {
            return null;
          }
        }
        break;
      }
    }
    
    return value;
  };

  const t = (key: string): string => {
    const value = getTranslationValue(key);
    return typeof value === 'string' ? value : key;
  };

  const tArray = (key: string): string[] => {
    const value = getTranslationValue(key);
    return Array.isArray(value) ? value : [];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tArray, isTransitioning }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Language display names
export const languageNames: Record<Language, string> = {
  en: 'English',
  id: 'Bahasa Indonesia',
  ms: 'Bahasa Malaysia',
  zh: '中文',
  ar: 'العربية',
  pt: 'Português (Brasil)',
};

// Translations
const translations: Record<Language, any> = {
  en: {
    nav: {
      home: 'Home',
      about: 'About Us',
      products: 'Products',
      whyChooseUs: 'Why Choose Us',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    home: {
      heroTitle: 'Trusted Global Supplier of',
      heroTitleHighlight: 'Coconut Derivatives',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - Your reliable partner for premium quality coconut products from Indonesia',
      viewProducts: 'View Our Products',
      highlights: {
        premiumQuality: 'Premium Quality',
        premiumQualityDesc: 'Stringent quality control for export-grade products',
        stableSupply: 'Stable Supply',
        stableSupplyDesc: 'Reliable sourcing network ensuring consistent delivery',
        competitivePricing: 'Competitive Pricing',
        competitivePricingDesc: 'Fair pricing with transparent business practices',
        exportReady: 'Export-Ready Supply Chain',
        exportReadyDesc: 'Premium product quality with export-ready compliance',
      },
      aboutTitle: 'About PT. Sukses Ekspor Mandiri',
      aboutDesc: 'We are a leading Indonesian exporter specializing in premium coconut derivatives. Operating from Malang, East Java, we serve global B2B buyers with commitment to quality, reliability, and professional service. Our extensive network of trusted suppliers and farmers ensures consistent supply of export-grade products.',
      learnMore: 'Learn More About Us',
      featuredTitle: 'Our Featured Products',
      featuredSubtitle: 'Premium quality coconut derivatives for global markets',
      viewAllProducts: 'View All Products',
      ctaTitle: 'Ready to Partner With Us?',
      ctaDesc: "Contact us today to discuss your coconut derivatives requirements. We're here to provide quality products and reliable service.",
      contactWhatsApp: 'Contact via WhatsApp',
      sendInquiry: 'Send Inquiry',
    },
    products: {
      semiHusked: 'Semi Husked Coconut',
      semiHuskedDesc: 'Premium quality semi husked coconuts for various industrial applications',
      desiccated: 'Desiccated Coconut',
      desiccatedDesc: 'Fresh coconut meat, finely processed for food industry',
      charcoal: 'Coconut Shell Charcoal',
      charcoalDesc: 'High-quality charcoal for industrial and commercial use',
      heroTitle: 'Our Products',
      heroSubtitle: 'Premium coconut derivatives for global B2B markets',
      applications: 'Applications:',
      keyFeatures: 'Key Features:',
      semiHuskedFullDesc: 'Premium quality semi husked coconuts sourced from trusted farms across Indonesia. Ideal for coconut water, copra production, and various industrial applications.',
      semiHuskedApps: 'Food processing, beverage industry, copra production, coconut oil manufacturing',
      semiHuskedFeatures: ['Export-grade quality', 'Properly selected and inspected', 'Consistent size and weight', 'Available year-round'],
      desiccatedFullDesc: 'Fresh coconut meat finely processed under strict hygiene standards. Perfect for food manufacturing and bakery industries.',
      desiccatedApps: 'Bakery products, confectionery, food manufacturing, dessert ingredients',
      desiccatedFeatures: ['Food-grade quality', 'Proper moisture content', 'Natural white color', 'Customizable particle size'],
      charcoalFullDesc: 'High-quality coconut shell charcoal produced from selected coconut shells. Excellent burning properties and consistent quality for industrial and commercial use.',
      charcoalApps: 'BBQ charcoal, activated carbon production, industrial fuel, shisha charcoal',
      charcoalFeatures: ['High carbon content', 'Low ash percentage', 'Long burning time', 'Consistent quality'],
      copraMeal: 'Copra Meal (Pellet and Powder)',
      copraMealDesc: 'Nutritious copra meal produced as a by-product of coconut oil extraction. Rich in protein and fiber, ideal for animal feed industries. Available in powder and pellet form.',
      copraMealApps: 'Livestock feed, poultry feed, aquaculture, animal nutrition',
      copraMealFeatures: ['High protein content', 'Natural and chemical-free', 'Consistent quality', 'Properly dried and processed'],
      crudeOil: 'Crude Coconut Oil',
      crudeOilDesc: 'Crude coconut oil is unrefined coconut oil extracted from dried mature coconut meat (copra). It maintains its natural properties and is widely used for industrial applications.',
      crudeOilApps: 'Soap manufacturing, cosmetics industry, biodiesel production, industrial lubricants',
      crudeOilFeatures: ['Natural extraction process', 'Consistent quality', 'Proper storage and packaging', 'Traceable sourcing'],
      inquiryNote: 'All products are available for export in bulk quantities. Pricing and detailed specifications are provided upon inquiry. We can accommodate custom packaging and specific requirements based on your needs.',
      requestInfo: 'Request Product Information',
      ctaTitle: 'Need a Custom Product Specification?',
      ctaDesc: 'We can accommodate specific requirements for volume, packaging, and quality specifications. Contact our team to discuss your needs.',
      whatsAppNow: 'WhatsApp Now',
    },
    about: {
      heroTitle: 'About PT. Sukses Ekspor Mandiri',
      heroSubtitle: 'Your Trusted Partner in Coconut Derivatives Export',
      whoWeAre: 'Who We Are',
      whoWeAreP1: 'PT. Sukses Ekspor Mandiri is a professional export company based in Malang, East Java, Indonesia, specializing in premium coconut derivatives. We serve B2B buyers worldwide including importers, distributors, and industrial manufacturers who require consistent supply of high-quality raw materials.',
      whoWeAreP2: "Our strategic location in Indonesia—one of the world's largest producers of coconut products—gives us direct access to the best sources. We work closely with a network of trusted farmers, processors, and suppliers to ensure that every shipment meets international quality standards.",
      philosophy: 'Our Business Philosophy',
      philosophyP1: 'We believe that successful business relationships are built on four pillars: integrity, quality, sustainability, and long-term partnership. Our goal is not just to sell products, but to become your reliable supplier partner who understands your needs and consistently delivers value.',
      philosophyP2: "Every buyer is unique, and we take time to understand your specific requirements—whether it's product specifications, packaging preferences, or delivery schedules. We're committed to providing transparent communication and professional service at every step of the process.",
      vision: 'Our Vision',
      visionText: 'To become a trusted and globally competitive Indonesian international trading company in providing coconut derivatives, while delivering added value to business partners worldwide.',
      mission: 'Our Mission',
      missionItems: [
        'Build long-term relationships with international buyers through professional service and consistent product quality.',
        'Strengthen partnerships with local producers to create a stable and transparent supply chain.',
        'Provide products that meet international quality standards with on-time delivery.',
        'Serve as a bridge between Indonesian producers and global markets, with a commitment to maintaining integrity in every transaction.',
        'Continuously expand our product portfolio in response to global market demands.',
      ],
      coreValues: 'Our Core Values',
      coreValuesSubtitle: 'The principles that form the foundation of all our business activities',
      integrity: 'Integrity',
      integrityDesc: 'Maintaining honesty and transparency in every business interaction.',
      quality: 'Quality',
      qualityDesc: 'Prioritizing specification compliance, product quality, and smooth delivery.',
      commitment: 'Commitment',
      commitmentDesc: 'Respecting time, agreements, and buyer needs.',
      partnership: 'Partnership',
      partnershipDesc: 'Building mutually supportive relationships with local producers and global partners.',
      commitmentsTitle: 'Our Commitments to You',
      commitmentsSubtitle: 'What you can expect when partnering with us',
      strictQC: 'Strict Quality Control',
      strictQCDesc: 'Every product undergoes rigorous inspection to meet international export standards',
      professional: 'Professional Standards',
      professionalDesc: 'Experienced team dedicated to providing excellent service and support',
      onTime: 'On-Time Shipment',
      onTimeDesc: 'Reliable logistics and supply chain management for timely delivery',
      sustainable: 'Sustainable Sourcing',
      sustainableDesc: 'Working with trusted farmers and suppliers who follow sustainable practices',
      locationTitle: 'Location & Operations',
      locationP1: 'Our headquarters and operations are based in Malang, East Java, Indonesia. This strategic location provides us with excellent access to major coconut production regions, as well as efficient logistics connections to international shipping ports.',
      locationP2: 'We maintain strong relationships with local suppliers and have established quality control processes at every stage—from sourcing raw materials to final packaging and shipment. Our experienced team ensures smooth operations and reliable service for all our international partners.',
      ctaTitle: "Let's Build a Partnership",
      ctaDesc: "Whether you're looking for a new supplier or want to diversify your sourcing, we're ready to discuss how we can meet your needs.",
      whatsAppUs: 'WhatsApp Us',
    },
    whyChooseUs: {
      heroTitle: 'Why Choose Us',
      heroSubtitle: 'Your trusted partner for quality coconut derivatives',
      premiumProducts: 'Premium Quality Products',
      premiumProductsDesc: 'Every product undergoes strict quality control to ensure it meets international export standards. We work only with reputable suppliers and maintain rigorous inspection processes from sourcing to shipment.',
      stableSupply: 'Stable & Reliable Supply',
      stableSupplyDesc: 'Our extensive network of farmers, processors, and suppliers ensures consistent availability year-round. We understand the importance of supply chain reliability for your business operations.',
      competitivePricing: 'Competitive Pricing',
      competitivePricingDesc: 'Direct relationships with source suppliers and efficient operations allow us to offer competitive prices without compromising quality. We believe in transparent, fair business practices.',
      exportReady: 'Export Ready Supply Chain',
      exportReadyDesc: 'Ready to support international buyers with professional handling of documentation, logistics, and technical requirements.',
      professionalService: 'Professional Service',
      professionalServiceDesc: 'From initial inquiry to delivery, we provide professional and responsive service. Our experienced team is dedicated to ensuring smooth transactions and building long-term partnerships.',
      trustedSourcing: 'Trusted Sourcing Network',
      trustedSourcingDesc: 'We maintain strong relationships with trusted farmers and suppliers who follow good agricultural practices. This ensures product quality while supporting sustainable sourcing.',
      processTitle: 'Our Working Process',
      processSubtitle: 'Simple, transparent, and professional process from inquiry to delivery',
      step1: 'Inquiry & Discussion',
      step1Desc: 'Share your product requirements, quantities, and specifications with us',
      step2: 'Quotation & Samples',
      step2Desc: 'Receive competitive pricing and product samples for evaluation if needed',
      step3: 'Order Confirmation',
      step3Desc: 'Confirm order details, payment terms, and delivery schedule',
      step4: 'Quality Control & Packaging',
      step4Desc: 'Products are inspected, properly packaged, and prepared for shipment',
      step5: 'Shipping & Documentation',
      step5Desc: 'Arrange logistics and provide all necessary export documentation',
      step6: 'After-Sales Support',
      step6Desc: 'Ongoing support for your satisfaction and future business needs',
      ctaTitle: 'Ready to Experience the Difference?',
      ctaDesc: 'Join our growing list of satisfied international buyers. Contact us today to discuss your coconut derivatives requirements.',
      chatWhatsApp: 'Chat on WhatsApp',
      sendInquiryNow: 'Send Inquiry Now',
    },
    gallery: {
      heroTitle: 'Gallery',
      heroSubtitle: 'See our products, production processes, and quality standards',
      category: 'Products',
      copraPellet: 'Copra Meal Pellet',
      copraPowder: 'Copra Meal Powder',
      crudeOil: 'Crude Coconut Oil',
      exportReadyTitle: 'Export Ready Supply Chain',
      exportReadyP1: 'We have developed an integrated supply chain system designed to support international buyers with clarity, efficiency, and professionalism. From quality control and export documentation preparation to logistics coordination and buyer communication, every process is structured to ensure smooth and secure transactions.',
      exportReadyP2: 'Whether you are an established importer or new to sourcing products from Indonesia, our team is ready to assist you at every stage to ensure that each order meets the agreed specifications and quality standards.',
      ctaTitle: 'Interested in Detailed Product Information?',
      ctaDesc: "Contact us for detailed product information, specifications, or to request samples. We're here to answer all your questions.",
      whatsAppUs: 'WhatsApp Us',
    },
    contact: {
      heroTitle: 'Contact Us',
      heroSubtitle: "Let's discuss how we can serve your coconut derivatives needs",
      getInTouch: 'Get in Touch',
      getInTouchDesc: 'We welcome inquiries from importers, distributors, and industrial buyers worldwide. Whether you have questions about our products, need a quotation, or want to discuss your specific requirements, our team is ready to assist you.',
      address: 'Address',
      addressValue: 'Malang, Jawa Timur, Indonesia',
      email: 'Email',
      whatsApp: 'WhatsApp',
      followUs: 'Follow Us',
      sendInquiry: 'Send an Inquiry',
      yourName: 'Your Name',
      emailAddress: 'Email Address',
      companyName: 'Company Name',
      country: 'Country',
      yourMessage: 'Your Message',
      messagePlaceholder: 'Please provide details about your inquiry, including product of interest, quantities, and any specific requirements...',
      sendInquiryNow: 'Send Inquiry Now',
      ctaTitle: 'Prefer to Chat Directly?',
      ctaDesc: "For faster response, feel free to contact us directly via WhatsApp. Our team is ready to answer your questions.",
      chatWhatsApp: 'Chat on WhatsApp',
    },
    footer: {
      tagline: 'Trusted Supplier Partner in Coconut Derivatives',
      quickLinks: 'Quick Links',
      contactUs: 'Contact Us',
      followUs: 'Follow Us',
      copyright: 'All rights reserved.',
    },
  },
  id: {
    nav: {
      home: 'Beranda',
      about: 'Tentang Kami',
      products: 'Produk',
      whyChooseUs: 'Mengapa Memilih Kami',
      gallery: 'Galeri',
      contact: 'Kontak',
    },
    home: {
      heroTitle: 'Pemasok Global Terpercaya untuk',
      heroTitleHighlight: 'Produk Turunan Kelapa',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - Mitra terpercaya Anda untuk produk kelapa berkualitas premium dari Indonesia',
      viewProducts: 'Lihat Produk Kami',
      highlights: {
        premiumQuality: 'Kualitas Premium',
        premiumQualityDesc: 'Kontrol kualitas ketat untuk produk berstandar ekspor',
        stableSupply: 'Pasokan Stabil',
        stableSupplyDesc: 'Jaringan pemasok terpercaya untuk pengiriman konsisten',
        competitivePricing: 'Harga Kompetitif',
        competitivePricingDesc: 'Harga wajar dengan praktik bisnis transparan',
        exportReady: 'Rantai Pasok Siap Ekspor',
        exportReadyDesc: 'Kualitas produk premium dengan kepatuhan siap ekspor',
      },
      aboutTitle: 'Tentang PT. Sukses Ekspor Mandiri',
      aboutDesc: 'Kami adalah eksportir Indonesia terkemuka yang mengkhususkan diri dalam produk turunan kelapa premium. Beroperasi dari Malang, Jawa Timur, kami melayani pembeli B2B global dengan komitmen terhadap kualitas, keandalan, dan layanan profesional. Jaringan pemasok dan petani terpercaya kami yang luas memastikan pasokan produk berstandar ekspor yang konsisten.',
      learnMore: 'Pelajari Lebih Lanjut',
      featuredTitle: 'Produk Unggulan Kami',
      featuredSubtitle: 'Produk turunan kelapa berkualitas premium untuk pasar global',
      viewAllProducts: 'Lihat Semua Produk',
      ctaTitle: 'Siap Bermitra Dengan Kami?',
      ctaDesc: 'Hubungi kami hari ini untuk mendiskusikan kebutuhan produk turunan kelapa Anda. Kami siap menyediakan produk berkualitas dan layanan yang andal.',
      contactWhatsApp: 'Hubungi via WhatsApp',
      sendInquiry: 'Kirim Pertanyaan',
    },
    products: {
      semiHusked: 'Kelapa Semi Kupas',
      semiHuskedDesc: 'Kelapa semi kupas berkualitas premium untuk berbagai aplikasi industri',
      desiccated: 'Kelapa Parut Kering',
      desiccatedDesc: 'Daging kelapa segar, diproses halus untuk industri makanan',
      charcoal: 'Arang Batok Kelapa',
      charcoalDesc: 'Arang berkualitas tinggi untuk penggunaan industri dan komersial',
      heroTitle: 'Produk Kami',
      heroSubtitle: 'Produk turunan kelapa premium untuk pasar B2B global',
      applications: 'Aplikasi:',
      keyFeatures: 'Fitur Utama:',
      semiHuskedFullDesc: 'Kelapa semi kupas berkualitas premium yang bersumber dari pertanian terpercaya di seluruh Indonesia. Ideal untuk air kelapa, produksi kopra, dan berbagai aplikasi industri.',
      semiHuskedApps: 'Pengolahan makanan, industri minuman, produksi kopra, pembuatan minyak kelapa',
      semiHuskedFeatures: ['Kualitas berstandar ekspor', 'Dipilih dan diperiksa dengan baik', 'Ukuran dan berat konsisten', 'Tersedia sepanjang tahun'],
      desiccatedFullDesc: 'Daging kelapa segar yang diproses halus dengan standar kebersihan ketat. Sempurna untuk industri makanan dan roti.',
      desiccatedApps: 'Produk roti, kembang gula, manufaktur makanan, bahan dessert',
      desiccatedFeatures: ['Kualitas food-grade', 'Kadar air yang tepat', 'Warna putih alami', 'Ukuran partikel dapat disesuaikan'],
      charcoalFullDesc: 'Arang batok kelapa berkualitas tinggi yang diproduksi dari batok kelapa pilihan. Sifat pembakaran yang sangat baik dan kualitas konsisten untuk penggunaan industri dan komersial.',
      charcoalApps: 'Arang BBQ, produksi karbon aktif, bahan bakar industri, arang shisha',
      charcoalFeatures: ['Kandungan karbon tinggi', 'Persentase abu rendah', 'Waktu pembakaran lama', 'Kualitas konsisten'],
      copraMeal: 'Bungkil Kopra (Pelet dan Bubuk)',
      copraMealDesc: 'Bungkil kopra bergizi yang diproduksi sebagai produk sampingan dari ekstraksi minyak kelapa. Kaya protein dan serat, ideal untuk industri pakan ternak. Tersedia dalam bentuk bubuk dan pelet.',
      copraMealApps: 'Pakan ternak, pakan unggas, akuakultur, nutrisi hewan',
      copraMealFeatures: ['Kandungan protein tinggi', 'Alami dan bebas bahan kimia', 'Kualitas konsisten', 'Dikeringkan dan diproses dengan baik'],
      crudeOil: 'Minyak Kelapa Mentah',
      crudeOilDesc: 'Minyak kelapa mentah adalah minyak kelapa murni yang diekstrak dari daging kelapa tua yang dikeringkan (kopra). Mempertahankan sifat alaminya dan banyak digunakan untuk aplikasi industri.',
      crudeOilApps: 'Pembuatan sabun, industri kosmetik, produksi biodiesel, pelumas industri',
      crudeOilFeatures: ['Proses ekstraksi alami', 'Kualitas konsisten', 'Penyimpanan dan pengemasan yang tepat', 'Sumber yang dapat dilacak'],
      inquiryNote: 'Semua produk tersedia untuk ekspor dalam jumlah besar. Harga dan spesifikasi detail diberikan berdasarkan permintaan. Kami dapat mengakomodasi pengemasan khusus dan persyaratan spesifik berdasarkan kebutuhan Anda.',
      requestInfo: 'Minta Informasi Produk',
      ctaTitle: 'Butuh Spesifikasi Produk Khusus?',
      ctaDesc: 'Kami dapat mengakomodasi persyaratan khusus untuk volume, pengemasan, dan spesifikasi kualitas. Hubungi tim kami untuk mendiskusikan kebutuhan Anda.',
      whatsAppNow: 'WhatsApp Sekarang',
    },
    about: {
      heroTitle: 'Tentang PT. Sukses Ekspor Mandiri',
      heroSubtitle: 'Mitra Terpercaya Anda dalam Ekspor Produk Turunan Kelapa',
      whoWeAre: 'Siapa Kami',
      whoWeAreP1: 'PT. Sukses Ekspor Mandiri adalah perusahaan ekspor profesional yang berbasis di Malang, Jawa Timur, Indonesia, yang mengkhususkan diri dalam produk turunan kelapa premium. Kami melayani pembeli B2B di seluruh dunia termasuk importir, distributor, dan produsen industri yang membutuhkan pasokan bahan baku berkualitas tinggi secara konsisten.',
      whoWeAreP2: 'Lokasi strategis kami di Indonesia—salah satu produsen produk kelapa terbesar di dunia—memberi kami akses langsung ke sumber terbaik. Kami bekerja sama erat dengan jaringan petani, pengolah, dan pemasok terpercaya untuk memastikan setiap pengiriman memenuhi standar kualitas internasional.',
      philosophy: 'Filosofi Bisnis Kami',
      philosophyP1: 'Kami percaya bahwa hubungan bisnis yang sukses dibangun di atas empat pilar: integritas, kualitas, keberlanjutan, dan kemitraan jangka panjang. Tujuan kami bukan hanya menjual produk, tetapi menjadi mitra pemasok andal yang memahami kebutuhan Anda dan secara konsisten memberikan nilai.',
      philosophyP2: 'Setiap pembeli itu unik, dan kami meluangkan waktu untuk memahami kebutuhan spesifik Anda—baik itu spesifikasi produk, preferensi pengemasan, atau jadwal pengiriman. Kami berkomitmen untuk menyediakan komunikasi transparan dan layanan profesional di setiap langkah proses.',
      vision: 'Visi Kami',
      visionText: 'Menjadi perusahaan perdagangan internasional Indonesia yang terpercaya dan kompetitif secara global dalam menyediakan produk turunan kelapa, sambil memberikan nilai tambah kepada mitra bisnis di seluruh dunia.',
      mission: 'Misi Kami',
      missionItems: [
        'Membangun hubungan jangka panjang dengan pembeli internasional melalui layanan profesional dan kualitas produk yang konsisten.',
        'Memperkuat kemitraan dengan produsen lokal untuk menciptakan rantai pasok yang stabil dan transparan.',
        'Menyediakan produk yang memenuhi standar kualitas internasional dengan pengiriman tepat waktu.',
        'Menjadi jembatan antara produsen Indonesia dan pasar global, dengan komitmen menjaga integritas dalam setiap transaksi.',
        'Terus memperluas portofolio produk sebagai respons terhadap permintaan pasar global.',
      ],
      coreValues: 'Nilai Inti Kami',
      coreValuesSubtitle: 'Prinsip-prinsip yang menjadi dasar semua aktivitas bisnis kami',
      integrity: 'Integritas',
      integrityDesc: 'Menjaga kejujuran dan transparansi dalam setiap interaksi bisnis.',
      quality: 'Kualitas',
      qualityDesc: 'Mengutamakan kepatuhan spesifikasi, kualitas produk, dan kelancaran pengiriman.',
      commitment: 'Komitmen',
      commitmentDesc: 'Menghormati waktu, perjanjian, dan kebutuhan pembeli.',
      partnership: 'Kemitraan',
      partnershipDesc: 'Membangun hubungan yang saling mendukung dengan produsen lokal dan mitra global.',
      commitmentsTitle: 'Komitmen Kami untuk Anda',
      commitmentsSubtitle: 'Apa yang dapat Anda harapkan saat bermitra dengan kami',
      strictQC: 'Kontrol Kualitas Ketat',
      strictQCDesc: 'Setiap produk menjalani inspeksi ketat untuk memenuhi standar ekspor internasional',
      professional: 'Standar Profesional',
      professionalDesc: 'Tim berpengalaman yang berdedikasi untuk memberikan layanan dan dukungan terbaik',
      onTime: 'Pengiriman Tepat Waktu',
      onTimeDesc: 'Logistik dan manajemen rantai pasok yang andal untuk pengiriman tepat waktu',
      sustainable: 'Sumber Berkelanjutan',
      sustainableDesc: 'Bekerja dengan petani dan pemasok terpercaya yang mengikuti praktik berkelanjutan',
      locationTitle: 'Lokasi & Operasional',
      locationP1: 'Kantor pusat dan operasional kami berbasis di Malang, Jawa Timur, Indonesia. Lokasi strategis ini memberi kami akses yang sangat baik ke daerah produksi kelapa utama, serta koneksi logistik yang efisien ke pelabuhan pengiriman internasional.',
      locationP2: 'Kami mempertahankan hubungan yang kuat dengan pemasok lokal dan telah menetapkan proses kontrol kualitas di setiap tahap—dari pengadaan bahan baku hingga pengemasan dan pengiriman akhir. Tim berpengalaman kami memastikan operasi yang lancar dan layanan yang andal untuk semua mitra internasional kami.',
      ctaTitle: 'Mari Bangun Kemitraan',
      ctaDesc: 'Baik Anda mencari pemasok baru atau ingin mendiversifikasi sumber Anda, kami siap mendiskusikan bagaimana kami dapat memenuhi kebutuhan Anda.',
      whatsAppUs: 'WhatsApp Kami',
    },
    whyChooseUs: {
      heroTitle: 'Mengapa Memilih Kami',
      heroSubtitle: 'Mitra terpercaya Anda untuk produk turunan kelapa berkualitas',
      premiumProducts: 'Produk Berkualitas Premium',
      premiumProductsDesc: 'Setiap produk menjalani kontrol kualitas ketat untuk memastikan memenuhi standar ekspor internasional. Kami hanya bekerja dengan pemasok terkemuka dan mempertahankan proses inspeksi yang ketat dari pengadaan hingga pengiriman.',
      stableSupply: 'Pasokan Stabil & Andal',
      stableSupplyDesc: 'Jaringan petani, pengolah, dan pemasok kami yang luas memastikan ketersediaan konsisten sepanjang tahun. Kami memahami pentingnya keandalan rantai pasok untuk operasi bisnis Anda.',
      competitivePricing: 'Harga Kompetitif',
      competitivePricingDesc: 'Hubungan langsung dengan pemasok sumber dan operasi yang efisien memungkinkan kami menawarkan harga kompetitif tanpa mengorbankan kualitas. Kami percaya pada praktik bisnis yang transparan dan adil.',
      exportReady: 'Rantai Pasok Siap Ekspor',
      exportReadyDesc: 'Siap mendukung pembeli internasional dengan penanganan profesional dokumentasi, logistik, dan persyaratan teknis.',
      professionalService: 'Layanan Profesional',
      professionalServiceDesc: 'Dari pertanyaan awal hingga pengiriman, kami memberikan layanan profesional dan responsif. Tim berpengalaman kami berdedikasi untuk memastikan transaksi lancar dan membangun kemitraan jangka panjang.',
      trustedSourcing: 'Jaringan Sumber Terpercaya',
      trustedSourcingDesc: 'Kami mempertahankan hubungan yang kuat dengan petani dan pemasok terpercaya yang mengikuti praktik pertanian yang baik. Ini memastikan kualitas produk sambil mendukung sumber yang berkelanjutan.',
      processTitle: 'Proses Kerja Kami',
      processSubtitle: 'Proses sederhana, transparan, dan profesional dari pertanyaan hingga pengiriman',
      step1: 'Pertanyaan & Diskusi',
      step1Desc: 'Bagikan kebutuhan produk, kuantitas, dan spesifikasi Anda kepada kami',
      step2: 'Penawaran & Sampel',
      step2Desc: 'Terima harga kompetitif dan sampel produk untuk evaluasi jika diperlukan',
      step3: 'Konfirmasi Pesanan',
      step3Desc: 'Konfirmasi detail pesanan, syarat pembayaran, dan jadwal pengiriman',
      step4: 'Kontrol Kualitas & Pengemasan',
      step4Desc: 'Produk diperiksa, dikemas dengan baik, dan disiapkan untuk pengiriman',
      step5: 'Pengiriman & Dokumentasi',
      step5Desc: 'Atur logistik dan sediakan semua dokumentasi ekspor yang diperlukan',
      step6: 'Dukungan Purna Jual',
      step6Desc: 'Dukungan berkelanjutan untuk kepuasan Anda dan kebutuhan bisnis masa depan',
      ctaTitle: 'Siap Merasakan Perbedaannya?',
      ctaDesc: 'Bergabunglah dengan daftar pembeli internasional kami yang puas. Hubungi kami hari ini untuk mendiskusikan kebutuhan produk turunan kelapa Anda.',
      chatWhatsApp: 'Chat di WhatsApp',
      sendInquiryNow: 'Kirim Pertanyaan Sekarang',
    },
    gallery: {
      heroTitle: 'Galeri',
      heroSubtitle: 'Lihat produk, proses produksi, dan standar kualitas kami',
      category: 'Produk',
      copraPellet: 'Bungkil Kopra Pelet',
      copraPowder: 'Bungkil Kopra Bubuk',
      crudeOil: 'Minyak Kelapa Mentah',
      exportReadyTitle: 'Rantai Pasok Siap Ekspor',
      exportReadyP1: 'Kami telah mengembangkan sistem rantai pasok terintegrasi yang dirancang untuk mendukung pembeli internasional dengan kejelasan, efisiensi, dan profesionalisme. Dari kontrol kualitas dan persiapan dokumentasi ekspor hingga koordinasi logistik dan komunikasi dengan pembeli, setiap proses terstruktur untuk memastikan transaksi yang lancar dan aman.',
      exportReadyP2: 'Baik Anda importir berpengalaman atau baru dalam pengadaan produk dari Indonesia, tim kami siap membantu Anda di setiap tahap untuk memastikan bahwa setiap pesanan memenuhi spesifikasi dan standar kualitas yang disepakati.',
      ctaTitle: 'Tertarik dengan Informasi Produk Terperinci?',
      ctaDesc: 'Hubungi kami untuk informasi produk terperinci, spesifikasi, atau untuk meminta sampel. Kami siap menjawab semua pertanyaan Anda.',
      whatsAppUs: 'WhatsApp Kami',
    },
    contact: {
      heroTitle: 'Hubungi Kami',
      heroSubtitle: 'Mari diskusikan bagaimana kami dapat melayani kebutuhan produk turunan kelapa Anda',
      getInTouch: 'Hubungi Kami',
      getInTouchDesc: 'Kami menyambut pertanyaan dari importir, distributor, dan pembeli industri di seluruh dunia. Baik Anda memiliki pertanyaan tentang produk kami, membutuhkan penawaran, atau ingin mendiskusikan kebutuhan spesifik Anda, tim kami siap membantu Anda.',
      address: 'Alamat',
      addressValue: 'Malang, Jawa Timur, Indonesia',
      email: 'Email',
      whatsApp: 'WhatsApp',
      followUs: 'Ikuti Kami',
      sendInquiry: 'Kirim Pertanyaan',
      yourName: 'Nama Anda',
      emailAddress: 'Alamat Email',
      companyName: 'Nama Perusahaan',
      country: 'Negara',
      yourMessage: 'Pesan Anda',
      messagePlaceholder: 'Harap berikan detail tentang pertanyaan Anda, termasuk produk yang diminati, kuantitas, dan persyaratan khusus...',
      sendInquiryNow: 'Kirim Pertanyaan Sekarang',
      ctaTitle: 'Lebih Suka Chat Langsung?',
      ctaDesc: 'Untuk respons lebih cepat, silakan hubungi kami langsung via WhatsApp. Tim kami siap menjawab pertanyaan Anda.',
      chatWhatsApp: 'Chat di WhatsApp',
    },
    footer: {
      tagline: 'Mitra Pemasok Terpercaya dalam Produk Turunan Kelapa',
      quickLinks: 'Tautan Cepat',
      contactUs: 'Hubungi Kami',
      followUs: 'Ikuti Kami',
      copyright: 'Hak cipta dilindungi.',
    },
  },
  ms: {
    nav: {
      home: 'Laman Utama',
      about: 'Tentang Kami',
      products: 'Produk',
      whyChooseUs: 'Mengapa Pilih Kami',
      gallery: 'Galeri',
      contact: 'Hubungi',
    },
    home: {
      heroTitle: 'Pembekal Global Dipercayai untuk',
      heroTitleHighlight: 'Derivatif Kelapa',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - Rakan kongsi anda yang boleh dipercayai untuk produk kelapa berkualiti premium dari Indonesia',
      viewProducts: 'Lihat Produk Kami',
      highlights: {
        premiumQuality: 'Kualiti Premium',
        premiumQualityDesc: 'Kawalan kualiti ketat untuk produk gred eksport',
        stableSupply: 'Bekalan Stabil',
        stableSupplyDesc: 'Rangkaian sumber yang boleh dipercayai memastikan penghantaran konsisten',
        competitivePricing: 'Harga Kompetitif',
        competitivePricingDesc: 'Harga berpatutan dengan amalan perniagaan telus',
        exportReady: 'Rantaian Bekalan Sedia Eksport',
        exportReadyDesc: 'Kualiti produk premium dengan pematuhan sedia eksport',
      },
      aboutTitle: 'Tentang PT. Sukses Ekspor Mandiri',
      aboutDesc: 'Kami adalah pengeksport Indonesia terkemuka yang mengkhusus dalam derivatif kelapa premium. Beroperasi dari Malang, Jawa Timur, kami melayani pembeli B2B global dengan komitmen terhadap kualiti, kebolehpercayaan, dan perkhidmatan profesional.',
      learnMore: 'Ketahui Lebih Lanjut',
      featuredTitle: 'Produk Unggulan Kami',
      featuredSubtitle: 'Derivatif kelapa berkualiti premium untuk pasaran global',
      viewAllProducts: 'Lihat Semua Produk',
      ctaTitle: 'Bersedia Bekerjasama Dengan Kami?',
      ctaDesc: 'Hubungi kami hari ini untuk membincangkan keperluan derivatif kelapa anda.',
      contactWhatsApp: 'Hubungi melalui WhatsApp',
      sendInquiry: 'Hantar Pertanyaan',
    },
    products: {
      semiHusked: 'Kelapa Separuh Kupas',
      semiHuskedDesc: 'Kelapa separuh kupas berkualiti premium untuk pelbagai aplikasi industri',
      desiccated: 'Kelapa Parut Kering',
      desiccatedDesc: 'Isi kelapa segar, diproses halus untuk industri makanan',
      charcoal: 'Arang Tempurung Kelapa',
      charcoalDesc: 'Arang berkualiti tinggi untuk kegunaan industri dan komersial',
      heroTitle: 'Produk Kami',
      heroSubtitle: 'Derivatif kelapa premium untuk pasaran B2B global',
      applications: 'Aplikasi:',
      keyFeatures: 'Ciri-ciri Utama:',
      semiHuskedFullDesc: 'Kelapa separuh kupas berkualiti premium yang diperoleh dari ladang dipercayai di seluruh Indonesia.',
      semiHuskedApps: 'Pemprosesan makanan, industri minuman, pengeluaran kopra, pembuatan minyak kelapa',
      semiHuskedFeatures: ['Kualiti gred eksport', 'Dipilih dan diperiksa dengan baik', 'Saiz dan berat konsisten', 'Tersedia sepanjang tahun'],
      desiccatedFullDesc: 'Isi kelapa segar yang diproses halus dengan standard kebersihan yang ketat.',
      desiccatedApps: 'Produk bakeri, kuih-muih, pembuatan makanan, bahan pencuci mulut',
      desiccatedFeatures: ['Kualiti gred makanan', 'Kandungan kelembapan yang sesuai', 'Warna putih semula jadi', 'Saiz zarah boleh disesuaikan'],
      charcoalFullDesc: 'Arang tempurung kelapa berkualiti tinggi yang dihasilkan dari tempurung kelapa terpilih.',
      charcoalApps: 'Arang BBQ, pengeluaran karbon aktif, bahan api industri, arang shisha',
      charcoalFeatures: ['Kandungan karbon tinggi', 'Peratusan abu rendah', 'Masa pembakaran lama', 'Kualiti konsisten'],
      copraMeal: 'Hampas Kopra (Pelet dan Serbuk)',
      copraMealDesc: 'Hampas kopra berkhasiat yang dihasilkan sebagai produk sampingan dari pengekstrakan minyak kelapa.',
      copraMealApps: 'Makanan ternakan, makanan ayam, akuakultur, nutrisi haiwan',
      copraMealFeatures: ['Kandungan protein tinggi', 'Semula jadi dan bebas bahan kimia', 'Kualiti konsisten', 'Dikeringkan dan diproses dengan baik'],
      crudeOil: 'Minyak Kelapa Mentah',
      crudeOilDesc: 'Minyak kelapa mentah adalah minyak kelapa tidak ditapis yang diekstrak dari isi kelapa matang yang dikeringkan.',
      crudeOilApps: 'Pembuatan sabun, industri kosmetik, pengeluaran biodiesel, pelincir industri',
      crudeOilFeatures: ['Proses pengekstrakan semula jadi', 'Kualiti konsisten', 'Penyimpanan dan pembungkusan yang betul', 'Sumber boleh dijejaki'],
      inquiryNote: 'Semua produk tersedia untuk eksport dalam kuantiti pukal.',
      requestInfo: 'Minta Maklumat Produk',
      ctaTitle: 'Perlukan Spesifikasi Produk Tersuai?',
      ctaDesc: 'Kami boleh menampung keperluan khusus untuk volum, pembungkusan, dan spesifikasi kualiti.',
      whatsAppNow: 'WhatsApp Sekarang',
    },
    about: {
      heroTitle: 'Tentang PT. Sukses Ekspor Mandiri',
      heroSubtitle: 'Rakan Kongsi Dipercayai Anda dalam Eksport Derivatif Kelapa',
      whoWeAre: 'Siapa Kami',
      whoWeAreP1: 'PT. Sukses Ekspor Mandiri adalah syarikat eksport profesional yang berpusat di Malang, Jawa Timur, Indonesia.',
      whoWeAreP2: 'Lokasi strategik kami di Indonesia memberi kami akses terus kepada sumber terbaik.',
      philosophy: 'Falsafah Perniagaan Kami',
      philosophyP1: 'Kami percaya bahawa hubungan perniagaan yang berjaya dibina atas empat tiang: integriti, kualiti, kelestarian, dan perkongsian jangka panjang.',
      philosophyP2: 'Setiap pembeli adalah unik, dan kami meluangkan masa untuk memahami keperluan khusus anda.',
      vision: 'Visi Kami',
      visionText: 'Menjadi syarikat perdagangan antarabangsa Indonesia yang dipercayai dan berdaya saing global.',
      mission: 'Misi Kami',
      missionItems: [
        'Membina hubungan jangka panjang dengan pembeli antarabangsa.',
        'Mengukuhkan perkongsian dengan pengeluar tempatan.',
        'Menyediakan produk yang memenuhi standard kualiti antarabangsa.',
        'Menjadi jambatan antara pengeluar Indonesia dan pasaran global.',
        'Terus mengembangkan portfolio produk kami.',
      ],
      coreValues: 'Nilai Teras Kami',
      coreValuesSubtitle: 'Prinsip-prinsip yang membentuk asas semua aktiviti perniagaan kami',
      integrity: 'Integriti',
      integrityDesc: 'Mengekalkan kejujuran dan ketelusan dalam setiap interaksi perniagaan.',
      quality: 'Kualiti',
      qualityDesc: 'Mengutamakan pematuhan spesifikasi, kualiti produk, dan penghantaran lancar.',
      commitment: 'Komitmen',
      commitmentDesc: 'Menghormati masa, perjanjian, dan keperluan pembeli.',
      partnership: 'Perkongsian',
      partnershipDesc: 'Membina hubungan yang saling menyokong.',
      commitmentsTitle: 'Komitmen Kami kepada Anda',
      commitmentsSubtitle: 'Apa yang boleh anda jangkakan apabila bekerjasama dengan kami',
      strictQC: 'Kawalan Kualiti Ketat',
      strictQCDesc: 'Setiap produk menjalani pemeriksaan ketat',
      professional: 'Standard Profesional',
      professionalDesc: 'Pasukan berpengalaman yang berdedikasi',
      onTime: 'Penghantaran Tepat Masa',
      onTimeDesc: 'Logistik dan pengurusan rantaian bekalan yang boleh dipercayai',
      sustainable: 'Sumber Lestari',
      sustainableDesc: 'Bekerja dengan petani dan pembekal yang dipercayai',
      locationTitle: 'Lokasi & Operasi',
      locationP1: 'Ibu pejabat dan operasi kami berpusat di Malang, Jawa Timur, Indonesia.',
      locationP2: 'Kami mengekalkan hubungan yang kukuh dengan pembekal tempatan.',
      ctaTitle: 'Mari Bina Perkongsian',
      ctaDesc: 'Kami bersedia membincangkan bagaimana kami boleh memenuhi keperluan anda.',
      whatsAppUs: 'WhatsApp Kami',
    },
    whyChooseUs: {
      heroTitle: 'Mengapa Pilih Kami',
      heroSubtitle: 'Rakan kongsi dipercayai anda untuk derivatif kelapa berkualiti',
      premiumProducts: 'Produk Berkualiti Premium',
      premiumProductsDesc: 'Setiap produk menjalani kawalan kualiti ketat.',
      stableSupply: 'Bekalan Stabil & Boleh Dipercayai',
      stableSupplyDesc: 'Rangkaian petani, pemproses, dan pembekal kami yang luas.',
      competitivePricing: 'Harga Kompetitif',
      competitivePricingDesc: 'Hubungan langsung dengan pembekal sumber.',
      exportReady: 'Rantaian Bekalan Sedia Eksport',
      exportReadyDesc: 'Bersedia menyokong pembeli antarabangsa.',
      professionalService: 'Perkhidmatan Profesional',
      professionalServiceDesc: 'Dari pertanyaan awal hingga penghantaran.',
      trustedSourcing: 'Rangkaian Sumber Dipercayai',
      trustedSourcingDesc: 'Kami mengekalkan hubungan yang kukuh.',
      processTitle: 'Proses Kerja Kami',
      processSubtitle: 'Proses yang mudah, telus, dan profesional',
      step1: 'Pertanyaan & Perbincangan',
      step1Desc: 'Kongsi keperluan produk anda dengan kami',
      step2: 'Sebut Harga & Sampel',
      step2Desc: 'Terima harga kompetitif dan sampel produk',
      step3: 'Pengesahan Pesanan',
      step3Desc: 'Sahkan butiran pesanan dan jadual penghantaran',
      step4: 'Kawalan Kualiti & Pembungkusan',
      step4Desc: 'Produk diperiksa dan dibungkus',
      step5: 'Penghantaran & Dokumentasi',
      step5Desc: 'Atur logistik dan sediakan dokumentasi',
      step6: 'Sokongan Selepas Jualan',
      step6Desc: 'Sokongan berterusan untuk kepuasan anda',
      ctaTitle: 'Bersedia Merasai Perbezaannya?',
      ctaDesc: 'Sertai senarai pembeli antarabangsa kami yang berpuas hati.',
      chatWhatsApp: 'Chat di WhatsApp',
      sendInquiryNow: 'Hantar Pertanyaan Sekarang',
    },
    gallery: {
      heroTitle: 'Galeri',
      heroSubtitle: 'Lihat produk, proses pengeluaran, dan standard kualiti kami',
      category: 'Produk',
      copraPellet: 'Hampas Kopra Pelet',
      copraPowder: 'Hampas Kopra Serbuk',
      crudeOil: 'Minyak Kelapa Mentah',
      exportReadyTitle: 'Rantaian Bekalan Sedia Eksport',
      exportReadyP1: 'Kami telah membangunkan sistem rantaian bekalan bersepadu.',
      exportReadyP2: 'Pasukan kami bersedia membantu anda di setiap peringkat.',
      ctaTitle: 'Berminat dengan Maklumat Produk Terperinci?',
      ctaDesc: 'Hubungi kami untuk maklumat produk terperinci atau untuk meminta sampel.',
      whatsAppUs: 'WhatsApp Kami',
    },
    contact: {
      heroTitle: 'Hubungi Kami',
      heroSubtitle: 'Mari bincangkan bagaimana kami boleh memenuhi keperluan derivatif kelapa anda',
      getInTouch: 'Hubungi Kami',
      getInTouchDesc: 'Kami mengalu-alukan pertanyaan dari pengimport, pengedar, dan pembeli industri di seluruh dunia.',
      address: 'Alamat',
      addressValue: 'Malang, Jawa Timur, Indonesia',
      email: 'E-mel',
      whatsApp: 'WhatsApp',
      followUs: 'Ikuti Kami',
      sendInquiry: 'Hantar Pertanyaan',
      yourName: 'Nama Anda',
      emailAddress: 'Alamat E-mel',
      companyName: 'Nama Syarikat',
      country: 'Negara',
      yourMessage: 'Mesej Anda',
      messagePlaceholder: 'Sila berikan butiran tentang pertanyaan anda...',
      sendInquiryNow: 'Hantar Pertanyaan Sekarang',
      ctaTitle: 'Lebih Suka Chat Terus?',
      ctaDesc: 'Untuk respons lebih cepat, hubungi kami terus melalui WhatsApp.',
      chatWhatsApp: 'Chat di WhatsApp',
    },
    footer: {
      tagline: 'Rakan Pembekal Dipercayai dalam Derivatif Kelapa',
      quickLinks: 'Pautan Pantas',
      contactUs: 'Hubungi Kami',
      followUs: 'Ikuti Kami',
      copyright: 'Hak cipta terpelihara.',
    },
  },
  zh: {
    nav: {
      home: '首页',
      about: '关于我们',
      products: '产品',
      whyChooseUs: '为什么选择我们',
      gallery: '画廊',
      contact: '联系我们',
    },
    home: {
      heroTitle: '值得信赖的全球供应商',
      heroTitleHighlight: '椰子衍生产品',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - 您在印度尼西亚优质椰子产品的可靠合作伙伴',
      viewProducts: '查看我们的产品',
      highlights: {
        premiumQuality: '优质品质',
        premiumQualityDesc: '严格的质量控制，确保出口级产品',
        stableSupply: '稳定供应',
        stableSupplyDesc: '可靠的采购网络，确保持续交付',
        competitivePricing: '有竞争力的价格',
        competitivePricingDesc: '公平定价，透明的商业惯例',
        exportReady: '出口就绪供应链',
        exportReadyDesc: '优质产品质量，符合出口合规要求',
      },
      aboutTitle: '关于 PT. Sukses Ekspor Mandiri',
      aboutDesc: '我们是印度尼西亚领先的出口商，专门从事优质椰子衍生产品。我们在东爪哇省玛琅运营，以质量、可靠性和专业服务为承诺，服务全球B2B买家。我们广泛的可信供应商和农民网络确保持续供应出口级产品。',
      learnMore: '了解更多',
      featuredTitle: '我们的特色产品',
      featuredSubtitle: '面向全球市场的优质椰子衍生产品',
      viewAllProducts: '查看所有产品',
      ctaTitle: '准备与我们合作？',
      ctaDesc: '立即联系我们，讨论您的椰子衍生产品需求。我们随时为您提供优质产品和可靠服务。',
      contactWhatsApp: '通过WhatsApp联系',
      sendInquiry: '发送询盘',
    },
    products: {
      semiHusked: '半去壳椰子',
      semiHuskedDesc: '优质半去壳椰子，适用于各种工业应用',
      desiccated: '椰蓉',
      desiccatedDesc: '新鲜椰肉，精细加工，适用于食品行业',
      charcoal: '椰壳炭',
      charcoalDesc: '优质木炭，适用于工业和商业用途',
      heroTitle: '我们的产品',
      heroSubtitle: '面向全球B2B市场的优质椰子衍生产品',
      applications: '应用：',
      keyFeatures: '主要特点：',
      semiHuskedFullDesc: '来自印度尼西亚可信农场的优质半去壳椰子。适用于椰子水、椰干生产和各种工业应用。',
      semiHuskedApps: '食品加工、饮料行业、椰干生产、椰子油制造',
      semiHuskedFeatures: ['出口级品质', '精心挑选和检验', '尺寸和重量一致', '全年供应'],
      desiccatedFullDesc: '在严格卫生标准下精细加工的新鲜椰肉。非常适合食品制造和烘焙行业。',
      desiccatedApps: '烘焙产品、糖果、食品制造、甜点配料',
      desiccatedFeatures: ['食品级品质', '适当的水分含量', '天然白色', '可定制颗粒大小'],
      charcoalFullDesc: '由精选椰壳生产的优质椰壳炭。燃烧性能优异，质量稳定，适用于工业和商业用途。',
      charcoalApps: '烧烤木炭、活性炭生产、工业燃料、水烟炭',
      charcoalFeatures: ['高碳含量', '低灰分', '燃烧时间长', '质量稳定'],
      copraMeal: '椰干粕（颗粒和粉末）',
      copraMealDesc: '营养丰富的椰干粕，是椰子油提取的副产品。富含蛋白质和纤维，适用于动物饲料行业。提供粉末和颗粒形式。',
      copraMealApps: '畜牧饲料、家禽饲料、水产养殖、动物营养',
      copraMealFeatures: ['高蛋白质含量', '天然无化学添加', '质量稳定', '充分干燥和加工'],
      crudeOil: '粗椰子油',
      crudeOilDesc: '粗椰子油是从干燥成熟椰肉（椰干）中提取的未精炼椰子油。保持其天然特性，广泛用于工业应用。',
      crudeOilApps: '肥皂制造、化妆品行业、生物柴油生产、工业润滑剂',
      crudeOilFeatures: ['天然提取工艺', '质量稳定', '适当的储存和包装', '可追溯来源'],
      inquiryNote: '所有产品均可大批量出口。价格和详细规格根据询盘提供。我们可以根据您的需求提供定制包装和特定要求。',
      requestInfo: '请求产品信息',
      ctaTitle: '需要定制产品规格？',
      ctaDesc: '我们可以满足特定的数量、包装和质量规格要求。联系我们的团队讨论您的需求。',
      whatsAppNow: '立即WhatsApp',
    },
    about: {
      heroTitle: '关于 PT. Sukses Ekspor Mandiri',
      heroSubtitle: '您在椰子衍生产品出口方面的可靠合作伙伴',
      whoWeAre: '我们是谁',
      whoWeAreP1: 'PT. Sukses Ekspor Mandiri是一家专业出口公司，总部位于印度尼西亚东爪哇省玛琅，专门从事优质椰子衍生产品。我们为全球B2B买家提供服务，包括进口商、分销商和工业制造商，他们需要持续供应高质量原材料。',
      whoWeAreP2: '我们在印度尼西亚的战略位置——世界上最大的椰子产品生产国之一——使我们能够直接获得最佳来源。我们与可信赖的农民、加工商和供应商网络密切合作，确保每批货物都符合国际质量标准。',
      philosophy: '我们的商业理念',
      philosophyP1: '我们相信，成功的商业关系建立在四个支柱上：诚信、质量、可持续性和长期合作伙伴关系。我们的目标不仅是销售产品，而是成为您可靠的供应商合作伙伴，了解您的需求并持续提供价值。',
      philosophyP2: '每个买家都是独特的，我们花时间了解您的具体需求——无论是产品规格、包装偏好还是交付时间表。我们致力于在流程的每个步骤提供透明的沟通和专业的服务。',
      vision: '我们的愿景',
      visionText: '成为值得信赖且具有全球竞争力的印度尼西亚国际贸易公司，提供椰子衍生产品，同时为全球商业伙伴提供附加价值。',
      mission: '我们的使命',
      missionItems: [
        '通过专业服务和一致的产品质量与国际买家建立长期关系。',
        '加强与当地生产商的合作伙伴关系，创建稳定透明的供应链。',
        '提供符合国际质量标准的产品，准时交付。',
        '作为印度尼西亚生产商和全球市场之间的桥梁，承诺在每笔交易中保持诚信。',
        '根据全球市场需求不断扩大我们的产品组合。',
      ],
      coreValues: '我们的核心价值观',
      coreValuesSubtitle: '构成我们所有商业活动基础的原则',
      integrity: '诚信',
      integrityDesc: '在每次商业互动中保持诚实和透明。',
      quality: '质量',
      qualityDesc: '优先考虑规格合规性、产品质量和顺畅交付。',
      commitment: '承诺',
      commitmentDesc: '尊重时间、协议和买家需求。',
      partnership: '合作伙伴关系',
      partnershipDesc: '与当地生产商和全球合作伙伴建立相互支持的关系。',
      commitmentsTitle: '我们对您的承诺',
      commitmentsSubtitle: '与我们合作时您可以期待的',
      strictQC: '严格的质量控制',
      strictQCDesc: '每个产品都经过严格检验，以满足国际出口标准',
      professional: '专业标准',
      professionalDesc: '经验丰富的团队致力于提供卓越的服务和支持',
      onTime: '准时发货',
      onTimeDesc: '可靠的物流和供应链管理，确保及时交付',
      sustainable: '可持续采购',
      sustainableDesc: '与遵循可持续实践的可信农民和供应商合作',
      locationTitle: '位置与运营',
      locationP1: '我们的总部和运营基地位于印度尼西亚东爪哇省玛琅。这一战略位置使我们能够很好地进入主要椰子产区，以及与国际航运港口的高效物流连接。',
      locationP2: '我们与当地供应商保持着牢固的关系，并在每个阶段建立了质量控制流程——从采购原材料到最终包装和发货。我们经验丰富的团队确保为所有国际合作伙伴提供顺畅的运营和可靠的服务。',
      ctaTitle: '让我们建立合作伙伴关系',
      ctaDesc: '无论您是在寻找新供应商还是想要多元化您的采购来源，我们随时准备讨论如何满足您的需求。',
      whatsAppUs: 'WhatsApp联系我们',
    },
    whyChooseUs: {
      heroTitle: '为什么选择我们',
      heroSubtitle: '您在优质椰子衍生产品方面的可信赖合作伙伴',
      premiumProducts: '优质产品',
      premiumProductsDesc: '每个产品都经过严格的质量控制，确保符合国际出口标准。我们只与信誉良好的供应商合作，并保持从采购到发货的严格检验流程。',
      stableSupply: '稳定可靠的供应',
      stableSupplyDesc: '我们广泛的农民、加工商和供应商网络确保全年持续可用。我们理解供应链可靠性对您业务运营的重要性。',
      competitivePricing: '有竞争力的价格',
      competitivePricingDesc: '与源头供应商的直接关系和高效运营使我们能够在不牺牲质量的情况下提供有竞争力的价格。我们相信透明、公平的商业惯例。',
      exportReady: '出口就绪供应链',
      exportReadyDesc: '准备好以专业方式处理文件、物流和技术要求，支持国际买家。',
      professionalService: '专业服务',
      professionalServiceDesc: '从初次询盘到交付，我们提供专业和及时的服务。我们经验丰富的团队致力于确保顺畅的交易并建立长期合作伙伴关系。',
      trustedSourcing: '可信采购网络',
      trustedSourcingDesc: '我们与遵循良好农业实践的可信农民和供应商保持着牢固的关系。这确保了产品质量，同时支持可持续采购。',
      processTitle: '我们的工作流程',
      processSubtitle: '从询盘到交付的简单、透明、专业流程',
      step1: '询盘与讨论',
      step1Desc: '与我们分享您的产品需求、数量和规格',
      step2: '报价与样品',
      step2Desc: '收到有竞争力的价格和产品样品以供评估（如需要）',
      step3: '订单确认',
      step3Desc: '确认订单详情、付款条款和交货时间表',
      step4: '质量控制与包装',
      step4Desc: '产品经过检验、妥善包装并准备发货',
      step5: '发货与文件',
      step5Desc: '安排物流并提供所有必要的出口文件',
      step6: '售后支持',
      step6Desc: '持续支持，确保您的满意和未来的业务需求',
      ctaTitle: '准备体验差异？',
      ctaDesc: '加入我们不断增长的满意国际买家名单。立即联系我们，讨论您的椰子衍生产品需求。',
      chatWhatsApp: '通过WhatsApp聊天',
      sendInquiryNow: '立即发送询盘',
    },
    gallery: {
      heroTitle: '画廊',
      heroSubtitle: '查看我们的产品、生产流程和质量标准',
      category: '产品',
      copraPellet: '椰干粕颗粒',
      copraPowder: '椰干粕粉末',
      crudeOil: '粗椰子油',
      exportReadyTitle: '出口就绪供应链',
      exportReadyP1: '我们已开发了一套综合供应链系统，旨在以清晰、高效和专业的方式支持国际买家。从质量控制和出口文件准备到物流协调和买家沟通，每个流程都经过精心设计，以确保顺畅和安全的交易。',
      exportReadyP2: '无论您是成熟的进口商还是初次从印度尼西亚采购产品，我们的团队随时准备在每个阶段为您提供帮助，确保每个订单都符合约定的规格和质量标准。',
      ctaTitle: '对详细产品信息感兴趣？',
      ctaDesc: '联系我们获取详细的产品信息、规格或请求样品。我们随时准备回答您的所有问题。',
      whatsAppUs: 'WhatsApp联系我们',
    },
    contact: {
      heroTitle: '联系我们',
      heroSubtitle: '让我们讨论如何满足您的椰子衍生产品需求',
      getInTouch: '联系我们',
      getInTouchDesc: '我们欢迎来自全球进口商、分销商和工业买家的询盘。无论您对我们的产品有疑问、需要报价还是想讨论您的具体需求，我们的团队随时准备为您提供帮助。',
      address: '地址',
      addressValue: '印度尼西亚东爪哇省玛琅',
      email: '电子邮件',
      whatsApp: 'WhatsApp',
      followUs: '关注我们',
      sendInquiry: '发送询盘',
      yourName: '您的姓名',
      emailAddress: '电子邮件地址',
      companyName: '公司名称',
      country: '国家',
      yourMessage: '您的留言',
      messagePlaceholder: '请提供您询盘的详细信息，包括感兴趣的产品、数量和任何具体要求...',
      sendInquiryNow: '立即发送询盘',
      ctaTitle: '更喜欢直接聊天？',
      ctaDesc: '为了更快的响应，请随时通过WhatsApp直接联系我们。我们的团队随时准备回答您的问题。',
      chatWhatsApp: '通过WhatsApp聊天',
    },
    footer: {
      tagline: '椰子衍生产品的可信赖供应商合作伙伴',
      quickLinks: '快速链接',
      contactUs: '联系我们',
      followUs: '关注我们',
      copyright: '保留所有权利。',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      about: 'من نحن',
      products: 'المنتجات',
      whyChooseUs: 'لماذا تختارنا',
      gallery: 'المعرض',
      contact: 'اتصل بنا',
    },
    home: {
      heroTitle: 'مورد عالمي موثوق لـ',
      heroTitleHighlight: 'مشتقات جوز الهند',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - شريكك الموثوق لمنتجات جوز الهند عالية الجودة من إندونيسيا',
      viewProducts: 'عرض منتجاتنا',
      highlights: {
        premiumQuality: 'جودة ممتازة',
        premiumQualityDesc: 'رقابة جودة صارمة للمنتجات المعدة للتصدير',
        stableSupply: 'إمداد مستقر',
        stableSupplyDesc: 'شبكة مصادر موثوقة تضمن التسليم المستمر',
        competitivePricing: 'أسعار تنافسية',
        competitivePricingDesc: 'تسعير عادل مع ممارسات تجارية شفافة',
        exportReady: 'سلسلة إمداد جاهزة للتصدير',
        exportReadyDesc: 'جودة منتج ممتازة مع امتثال جاهز للتصدير',
      },
      aboutTitle: 'عن PT. Sukses Ekspor Mandiri',
      aboutDesc: 'نحن مصدر إندونيسي رائد متخصص في مشتقات جوز الهند الممتازة. نعمل من مالانج، جاوة الشرقية، ونخدم المشترين العالميين B2B بالتزام بالجودة والموثوقية والخدمة المهنية.',
      learnMore: 'اعرف المزيد',
      featuredTitle: 'منتجاتنا المميزة',
      featuredSubtitle: 'مشتقات جوز الهند عالية الجودة للأسواق العالمية',
      viewAllProducts: 'عرض جميع المنتجات',
      ctaTitle: 'مستعد للشراكة معنا؟',
      ctaDesc: 'اتصل بنا اليوم لمناقشة احتياجاتك من مشتقات جوز الهند.',
      contactWhatsApp: 'تواصل عبر واتساب',
      sendInquiry: 'إرسال استفسار',
    },
    products: {
      semiHusked: 'جوز الهند نصف المقشر',
      semiHuskedDesc: 'جوز هند نصف مقشر عالي الجودة لمختلف التطبيقات الصناعية',
      desiccated: 'جوز الهند المجفف',
      desiccatedDesc: 'لب جوز الهند الطازج، معالج بدقة لصناعة الأغذية',
      charcoal: 'فحم قشر جوز الهند',
      charcoalDesc: 'فحم عالي الجودة للاستخدام الصناعي والتجاري',
      heroTitle: 'منتجاتنا',
      heroSubtitle: 'مشتقات جوز الهند الممتازة لأسواق B2B العالمية',
      applications: 'التطبيقات:',
      keyFeatures: 'الميزات الرئيسية:',
      semiHuskedFullDesc: 'جوز هند نصف مقشر عالي الجودة من مزارع موثوقة في جميع أنحاء إندونيسيا.',
      semiHuskedApps: 'تجهيز الأغذية، صناعة المشروبات، إنتاج الكوبرا، تصنيع زيت جوز الهند',
      semiHuskedFeatures: ['جودة معدة للتصدير', 'مختارة ومفحوصة بعناية', 'حجم ووزن متسق', 'متاح على مدار السنة'],
      desiccatedFullDesc: 'لب جوز الهند الطازج المعالج بدقة وفق معايير صحية صارمة.',
      desiccatedApps: 'منتجات المخابز، الحلويات، تصنيع الأغذية، مكونات الحلويات',
      desiccatedFeatures: ['جودة غذائية', 'محتوى رطوبة مناسب', 'لون أبيض طبيعي', 'حجم جزيئات قابل للتخصيص'],
      charcoalFullDesc: 'فحم قشر جوز الهند عالي الجودة المنتج من قشور جوز الهند المختارة.',
      charcoalApps: 'فحم الشواء، إنتاج الكربون النشط، الوقود الصناعي، فحم الشيشة',
      charcoalFeatures: ['محتوى كربون عالي', 'نسبة رماد منخفضة', 'وقت احتراق طويل', 'جودة متسقة'],
      copraMeal: 'وجبة الكوبرا (حبيبات ومسحوق)',
      copraMealDesc: 'وجبة كوبرا مغذية تنتج كمنتج ثانوي لاستخراج زيت جوز الهند.',
      copraMealApps: 'علف الماشية، علف الدواجن، تربية الأحياء المائية، تغذية الحيوانات',
      copraMealFeatures: ['محتوى بروتين عالي', 'طبيعي وخالي من المواد الكيميائية', 'جودة متسقة', 'مجفف ومعالج بشكل صحيح'],
      crudeOil: 'زيت جوز الهند الخام',
      crudeOilDesc: 'زيت جوز الهند الخام هو زيت جوز هند غير مكرر مستخرج من لب جوز الهند الناضج المجفف.',
      crudeOilApps: 'تصنيع الصابون، صناعة مستحضرات التجميل، إنتاج الديزل الحيوي، زيوت التشحيم الصناعية',
      crudeOilFeatures: ['عملية استخراج طبيعية', 'جودة متسقة', 'تخزين وتغليف مناسب', 'مصدر قابل للتتبع'],
      inquiryNote: 'جميع المنتجات متاحة للتصدير بكميات كبيرة.',
      requestInfo: 'طلب معلومات المنتج',
      ctaTitle: 'تحتاج مواصفات منتج مخصصة؟',
      ctaDesc: 'يمكننا استيعاب متطلبات محددة للحجم والتغليف ومواصفات الجودة.',
      whatsAppNow: 'واتساب الآن',
    },
    about: {
      heroTitle: 'عن PT. Sukses Ekspor Mandiri',
      heroSubtitle: 'شريكك الموثوق في تصدير مشتقات جوز الهند الممتازة',
      whoWeAre: 'من نحن',
      whoWeAreP1: 'PT. Sukses Ekspor Mandiri هي شركة تصدير محترفة مقرها في مالانج، جاوة الشرقية، إندونيسيا، متخصصة في مشتقات جوز الهند الممتازة. نخدم المشترين B2B في جميع أنحاء العالم بما في ذلك المستوردين والموزعين والمصنعين الصناعيين الذين يحتاجون إلى إمداد مستمر من المواد الخام عالية الجودة.',
      whoWeAreP2: 'موقعنا الاستراتيجي في إندونيسيا—أحد أكبر منتجي منتجات جوز الهند في العالم—يمنحنا وصولاً مباشراً إلى أفضل المصادر. نعمل بشكل وثيق مع شبكة من المزارعين والمعالجين والموردين الموثوقين لضمان أن كل شحنة تلبي معايير الجودة الدولية.',
      philosophy: 'فلسفتنا التجارية',
      philosophyP1: 'نؤمن بأن العلاقات التجارية الناجحة تُبنى على أربعة أركان: النزاهة والجودة والاستدامة والشراكة طويلة الأمد. هدفنا ليس فقط بيع المنتجات، بل أن نصبح شريك التوريد الموثوق الذي يفهم احتياجاتك ويقدم القيمة باستمرار.',
      philosophyP2: 'كل مشتري فريد، ونأخذ الوقت لفهم متطلباتك المحددة—سواء كانت مواصفات المنتج أو تفضيلات التغليف أو جداول التسليم. نحن ملتزمون بتوفير تواصل شفاف وخدمة مهنية في كل خطوة من العملية.',
      vision: 'رؤيتنا',
      visionText: 'أن نصبح شركة تجارة دولية إندونيسية موثوقة ومنافسة عالمياً في توفير مشتقات جوز الهند، مع تقديم قيمة مضافة للشركاء التجاريين في جميع أنحاء العالم.',
      mission: 'مهمتنا',
      missionItems: [
        'بناء علاقات طويلة الأمد مع المشترين الدوليين من خلال الخدمة المهنية وجودة المنتج المتسقة.',
        'تعزيز الشراكات مع المنتجين المحليين لإنشاء سلسلة إمداد مستقرة وشفافة.',
        'توفير منتجات تلبي معايير الجودة الدولية مع التسليم في الوقت المحدد.',
        'العمل كجسر بين المنتجين الإندونيسيين والأسواق العالمية، مع الالتزام بالنزاهة في كل معاملة.',
        'التوسع المستمر في محفظة منتجاتنا استجابة لمتطلبات السوق العالمية.',
      ],
      coreValues: 'قيمنا الأساسية',
      coreValuesSubtitle: 'المبادئ التي تشكل أساس جميع أنشطتنا التجارية',
      integrity: 'النزاهة',
      integrityDesc: 'الحفاظ على الصدق والشفافية في كل تعامل تجاري.',
      quality: 'الجودة',
      qualityDesc: 'إعطاء الأولوية للامتثال للمواصفات وجودة المنتج والتسليم السلس.',
      commitment: 'الالتزام',
      commitmentDesc: 'احترام الوقت والاتفاقيات واحتياجات المشتري.',
      partnership: 'الشراكة',
      partnershipDesc: 'بناء علاقات داعمة متبادلة مع المنتجين المحليين والشركاء العالميين.',
      commitmentsTitle: 'التزاماتنا تجاهك',
      commitmentsSubtitle: 'ما يمكنك توقعه عند الشراكة معنا',
      strictQC: 'رقابة جودة صارمة',
      strictQCDesc: 'كل منتج يخضع لفحص دقيق لتلبية معايير التصدير الدولية',
      professional: 'معايير مهنية',
      professionalDesc: 'فريق ذو خبرة ملتزم بتقديم خدمة ودعم ممتازين',
      onTime: 'شحن في الوقت المحدد',
      onTimeDesc: 'لوجستيات موثوقة وإدارة سلسلة إمداد للتسليم في الوقت المناسب',
      sustainable: 'مصادر مستدامة',
      sustainableDesc: 'العمل مع مزارعين وموردين موثوقين يتبعون الممارسات المستدامة',
      locationTitle: 'الموقع والعمليات',
      locationP1: 'يقع مقرنا الرئيسي وعملياتنا في مالانج، جاوة الشرقية، إندونيسيا. هذا الموقع الاستراتيجي يوفر لنا وصولاً ممتازاً إلى مناطق إنتاج جوز الهند الرئيسية، بالإضافة إلى اتصالات لوجستية فعالة مع موانئ الشحن الدولية.',
      locationP2: 'نحافظ على علاقات قوية مع الموردين المحليين وقد أنشأنا عمليات رقابة الجودة في كل مرحلة—من توريد المواد الخام إلى التغليف والشحن النهائي. فريقنا ذو الخبرة يضمن عمليات سلسة وخدمة موثوقة لجميع شركائنا الدوليين.',
      ctaTitle: 'لنبني شراكة معاً',
      ctaDesc: 'سواء كنت تبحث عن مورد جديد أو تريد تنويع مصادرك، نحن مستعدون لمناقشة كيف يمكننا تلبية احتياجاتك.',
      whatsAppUs: 'تواصل عبر واتساب',
    },
    whyChooseUs: {
      heroTitle: 'لماذا تختارنا',
      heroSubtitle: 'شريكك الموثوق لمشتقات جوز الهند عالية الجودة',
      premiumProducts: 'منتجات بجودة ممتازة',
      premiumProductsDesc: 'كل منتج يخضع لرقابة جودة صارمة لضمان استيفائه لمعايير التصدير الدولية. نعمل فقط مع موردين ذوي سمعة طيبة ونحافظ على عمليات فحص صارمة من التوريد إلى الشحن.',
      stableSupply: 'إمداد مستقر وموثوق',
      stableSupplyDesc: 'شبكتنا الواسعة من المزارعين والمعالجين والموردين تضمن توافراً مستمراً على مدار السنة. نفهم أهمية موثوقية سلسلة الإمداد لعمليات أعمالك.',
      competitivePricing: 'أسعار تنافسية',
      competitivePricingDesc: 'العلاقات المباشرة مع موردي المصدر والعمليات الفعالة تتيح لنا تقديم أسعار تنافسية دون المساومة على الجودة. نؤمن بالممارسات التجارية الشفافة والعادلة.',
      exportReady: 'سلسلة إمداد جاهزة للتصدير',
      exportReadyDesc: 'جاهزون لدعم المشترين الدوليين بالتعامل المهني مع الوثائق واللوجستيات والمتطلبات الفنية.',
      professionalService: 'خدمة مهنية',
      professionalServiceDesc: 'من الاستفسار الأول حتى التسليم، نقدم خدمة مهنية وسريعة الاستجابة. فريقنا ذو الخبرة ملتزم بضمان معاملات سلسة وبناء شراكات طويلة الأمد.',
      trustedSourcing: 'شبكة توريد موثوقة',
      trustedSourcingDesc: 'نحافظ على علاقات قوية مع مزارعين وموردين موثوقين يتبعون الممارسات الزراعية الجيدة. هذا يضمن جودة المنتج مع دعم المصادر المستدامة.',
      processTitle: 'عملية العمل لدينا',
      processSubtitle: 'عملية بسيطة وشفافة ومهنية من الاستفسار إلى التسليم',
      step1: 'الاستفسار والنقاش',
      step1Desc: 'شارك متطلبات منتجاتك وكمياتها ومواصفاتها معنا',
      step2: 'عرض الأسعار والعينات',
      step2Desc: 'احصل على أسعار تنافسية وعينات منتجات للتقييم إذا لزم الأمر',
      step3: 'تأكيد الطلب',
      step3Desc: 'تأكيد تفاصيل الطلب وشروط الدفع وجدول التسليم',
      step4: 'رقابة الجودة والتغليف',
      step4Desc: 'يتم فحص المنتجات وتغليفها بشكل صحيح وتجهيزها للشحن',
      step5: 'الشحن والتوثيق',
      step5Desc: 'ترتيب اللوجستيات وتوفير جميع وثائق التصدير اللازمة',
      step6: 'دعم ما بعد البيع',
      step6Desc: 'دعم مستمر لرضاك واحتياجات أعمالك المستقبلية',
      ctaTitle: 'مستعد لتجربة الفرق؟',
      ctaDesc: 'انضم إلى قائمتنا المتنامية من المشترين الدوليين الراضين. اتصل بنا اليوم لمناقشة احتياجاتك من مشتقات جوز الهند.',
      chatWhatsApp: 'دردشة عبر واتساب',
      sendInquiryNow: 'أرسل استفساراً الآن',
    },
    gallery: {
      heroTitle: 'معرض الصور',
      heroSubtitle: 'شاهد منتجاتنا وعمليات الإنتاج ومعايير الجودة لدينا',
      category: 'المنتجات',
      copraPellet: 'حبيبات بقايا الكوبرا',
      copraPowder: 'مسحوق بقايا الكوبرا',
      crudeOil: 'زيت جوز الهند الخام',
      exportReadyTitle: 'سلسلة إمداد جاهزة للتصدير',
      exportReadyP1: 'لقد طورنا نظام سلسلة إمداد متكامل مصمم لدعم المشترين الدوليين بالوضوح والكفاءة والاحترافية. من رقابة الجودة وإعداد وثائق التصدير إلى تنسيق اللوجستيات والتواصل مع المشترين، كل عملية منظمة لضمان معاملات سلسة وآمنة.',
      exportReadyP2: 'سواء كنت مستورداً راسخاً أو جديداً في توريد المنتجات من إندونيسيا، فريقنا جاهز لمساعدتك في كل مرحلة لضمان أن كل طلب يلبي المواصفات ومعايير الجودة المتفق عليها.',
      ctaTitle: 'مهتم بمعلومات المنتج التفصيلية؟',
      ctaDesc: 'اتصل بنا للحصول على معلومات المنتج التفصيلية والمواصفات أو لطلب عينات. نحن هنا للإجابة على جميع أسئلتك.',
      whatsAppUs: 'تواصل عبر واتساب',
    },
    contact: {
      heroTitle: 'اتصل بنا',
      heroSubtitle: 'دعنا نناقش كيف يمكننا خدمة احتياجاتك من مشتقات جوز الهند',
      getInTouch: 'تواصل معنا',
      getInTouchDesc: 'نرحب بالاستفسارات من المستوردين والموزعين والمشترين الصناعيين في جميع أنحاء العالم.',
      address: 'العنوان',
      addressValue: 'مالانج، جاوة الشرقية، إندونيسيا',
      email: 'البريد الإلكتروني',
      whatsApp: 'واتساب',
      followUs: 'تابعنا',
      sendInquiry: 'إرسال استفسار',
      yourName: 'اسمك',
      emailAddress: 'عنوان البريد الإلكتروني',
      companyName: 'اسم الشركة',
      country: 'البلد',
      yourMessage: 'رسالتك',
      messagePlaceholder: 'يرجى تقديم تفاصيل حول استفسارك...',
      sendInquiryNow: 'أرسل الاستفسار الآن',
      ctaTitle: 'تفضل الدردشة مباشرة؟',
      ctaDesc: 'للحصول على رد أسرع، تواصل معنا مباشرة عبر واتساب.',
      chatWhatsApp: 'دردش عبر واتساب',
    },
    footer: {
      tagline: 'شريك مورد موثوق في مشتقات جوز الهند',
      quickLinks: 'روابط سريعة',
      contactUs: 'اتصل بنا',
      followUs: 'تابعنا',
      copyright: 'جميع الحقوق محفوظة.',
    },
  },
  pt: {
    nav: {
      home: 'Início',
      about: 'Sobre Nós',
      products: 'Produtos',
      whyChooseUs: 'Por Que Nos Escolher',
      gallery: 'Galeria',
      contact: 'Contato',
    },
    home: {
      heroTitle: 'Fornecedor Global Confiável de',
      heroTitleHighlight: 'Derivados de Coco',
      heroSubtitle: 'PT. Sukses Ekspor Mandiri - Seu parceiro confiável para produtos de coco de alta qualidade da Indonésia',
      viewProducts: 'Ver Nossos Produtos',
      highlights: {
        premiumQuality: 'Qualidade Premium',
        premiumQualityDesc: 'Controle de qualidade rigoroso para produtos de exportação',
        stableSupply: 'Fornecimento Estável',
        stableSupplyDesc: 'Rede de fornecimento confiável garantindo entrega consistente',
        competitivePricing: 'Preços Competitivos',
        competitivePricingDesc: 'Preços justos com práticas comerciais transparentes',
        exportReady: 'Cadeia de Suprimentos Pronta para Exportação',
        exportReadyDesc: 'Qualidade de produto premium com conformidade de exportação',
      },
      aboutTitle: 'Sobre PT. Sukses Ekspor Mandiri',
      aboutDesc: 'Somos um exportador indonésio líder especializado em derivados de coco premium. Operando a partir de Malang, Java Oriental, atendemos compradores B2B globais com compromisso de qualidade, confiabilidade e serviço profissional.',
      learnMore: 'Saiba Mais',
      featuredTitle: 'Nossos Produtos em Destaque',
      featuredSubtitle: 'Derivados de coco de qualidade premium para mercados globais',
      viewAllProducts: 'Ver Todos os Produtos',
      ctaTitle: 'Pronto para Ser Nosso Parceiro?',
      ctaDesc: 'Entre em contato conosco hoje para discutir suas necessidades de derivados de coco.',
      contactWhatsApp: 'Contato via WhatsApp',
      sendInquiry: 'Enviar Consulta',
    },
    products: {
      semiHusked: 'Coco Semi Descascado',
      semiHuskedDesc: 'Cocos semi descascados de qualidade premium para diversas aplicações industriais',
      desiccated: 'Coco Ralado Seco',
      desiccatedDesc: 'Polpa de coco fresca, finamente processada para a indústria alimentícia',
      charcoal: 'Carvão de Casca de Coco',
      charcoalDesc: 'Carvão de alta qualidade para uso industrial e comercial',
      heroTitle: 'Nossos Produtos',
      heroSubtitle: 'Derivados de coco premium para mercados B2B globais',
      applications: 'Aplicações:',
      keyFeatures: 'Características Principais:',
      semiHuskedFullDesc: 'Cocos semi descascados de qualidade premium provenientes de fazendas confiáveis em toda a Indonésia.',
      semiHuskedApps: 'Processamento de alimentos, indústria de bebidas, produção de copra, fabricação de óleo de coco',
      semiHuskedFeatures: ['Qualidade de exportação', 'Selecionados e inspecionados', 'Tamanho e peso consistentes', 'Disponível o ano todo'],
      desiccatedFullDesc: 'Polpa de coco fresca finamente processada sob rigorosos padrões de higiene.',
      desiccatedApps: 'Produtos de panificação, confeitaria, fabricação de alimentos, ingredientes de sobremesas',
      desiccatedFeatures: ['Qualidade alimentar', 'Teor de umidade adequado', 'Cor branca natural', 'Tamanho de partícula personalizável'],
      charcoalFullDesc: 'Carvão de casca de coco de alta qualidade produzido a partir de cascas de coco selecionadas.',
      charcoalApps: 'Carvão para churrasco, produção de carvão ativado, combustível industrial, carvão para narguilé',
      charcoalFeatures: ['Alto teor de carbono', 'Baixa porcentagem de cinzas', 'Longo tempo de queima', 'Qualidade consistente'],
      copraMeal: 'Farelo de Copra (Pellet e Pó)',
      copraMealDesc: 'Farelo de copra nutritivo produzido como subproduto da extração de óleo de coco.',
      copraMealApps: 'Ração para gado, ração para aves, aquicultura, nutrição animal',
      copraMealFeatures: ['Alto teor de proteína', 'Natural e livre de químicos', 'Qualidade consistente', 'Devidamente seco e processado'],
      crudeOil: 'Óleo de Coco Bruto',
      crudeOilDesc: 'Óleo de coco bruto é óleo de coco não refinado extraído da polpa de coco maduro seco.',
      crudeOilApps: 'Fabricação de sabão, indústria de cosméticos, produção de biodiesel, lubrificantes industriais',
      crudeOilFeatures: ['Processo de extração natural', 'Qualidade consistente', 'Armazenamento e embalagem adequados', 'Origem rastreável'],
      inquiryNote: 'Todos os produtos estão disponíveis para exportação em quantidades a granel.',
      requestInfo: 'Solicitar Informações do Produto',
      ctaTitle: 'Precisa de Especificação Personalizada?',
      ctaDesc: 'Podemos acomodar requisitos específicos de volume, embalagem e especificações de qualidade.',
      whatsAppNow: 'WhatsApp Agora',
    },
    about: {
      heroTitle: 'Sobre a PT. Sukses Ekspor Mandiri',
      heroSubtitle: 'Seu Parceiro Confiável na Exportação de Derivados de Coco Premium',
      whoWeAre: 'Quem Somos',
      whoWeAreP1: 'A PT. Sukses Ekspor Mandiri é uma empresa exportadora profissional sediada em Malang, Java Oriental, Indonésia, especializada em derivados de coco premium. Atendemos compradores B2B em todo o mundo, incluindo importadores, distribuidores e fabricantes industriais que necessitam de fornecimento consistente de matérias-primas de alta qualidade.',
      whoWeAreP2: 'Nossa localização estratégica na Indonésia—um dos maiores produtores mundiais de produtos de coco—nos proporciona acesso direto às melhores fontes. Trabalhamos em estreita colaboração com uma rede de agricultores, processadores e fornecedores confiáveis para garantir que cada remessa atenda aos padrões internacionais de qualidade.',
      philosophy: 'Nossa Filosofia de Negócios',
      philosophyP1: 'Acreditamos que relacionamentos comerciais bem-sucedidos são construídos sobre quatro pilares: integridade, qualidade, sustentabilidade e parceria de longo prazo. Nosso objetivo não é apenas vender produtos, mas tornar-nos seu parceiro fornecedor confiável que entende suas necessidades e entrega valor consistentemente.',
      philosophyP2: 'Cada comprador é único, e dedicamos tempo para entender suas necessidades específicas—sejam especificações de produto, preferências de embalagem ou cronogramas de entrega. Estamos comprometidos em fornecer comunicação transparente e serviço profissional em cada etapa do processo.',
      vision: 'Nossa Visão',
      visionText: 'Tornar-se uma empresa de comércio internacional indonésia confiável e globalmente competitiva no fornecimento de derivados de coco, entregando valor agregado aos parceiros comerciais em todo o mundo.',
      mission: 'Nossa Missão',
      missionItems: [
        'Construir relacionamentos de longo prazo com compradores internacionais através de serviço profissional e qualidade de produto consistente.',
        'Fortalecer parcerias com produtores locais para criar uma cadeia de suprimentos estável e transparente.',
        'Fornecer produtos que atendam aos padrões internacionais de qualidade com entrega pontual.',
        'Servir como ponte entre produtores indonésios e mercados globais, com compromisso de manter integridade em cada transação.',
        'Expandir continuamente nosso portfólio de produtos em resposta às demandas do mercado global.',
      ],
      coreValues: 'Nossos Valores Fundamentais',
      coreValuesSubtitle: 'Os princípios que formam a base de todas as nossas atividades comerciais',
      integrity: 'Integridade',
      integrityDesc: 'Manter honestidade e transparência em cada interação comercial.',
      quality: 'Qualidade',
      qualityDesc: 'Priorizar conformidade de especificações, qualidade do produto e entrega suave.',
      commitment: 'Compromisso',
      commitmentDesc: 'Respeitar tempo, acordos e necessidades do comprador.',
      partnership: 'Parceria',
      partnershipDesc: 'Construir relacionamentos mutuamente benéficos com produtores locais e parceiros globais.',
      commitmentsTitle: 'Nossos Compromissos com Você',
      commitmentsSubtitle: 'O que você pode esperar ao trabalhar conosco',
      strictQC: 'Controle de Qualidade Rigoroso',
      strictQCDesc: 'Cada produto passa por inspeção rigorosa para atender aos padrões internacionais de exportação',
      professional: 'Padrões Profissionais',
      professionalDesc: 'Equipe experiente dedicada a fornecer excelente serviço e suporte',
      onTime: 'Envio Pontual',
      onTimeDesc: 'Logística confiável e gestão da cadeia de suprimentos para entrega pontual',
      sustainable: 'Fornecimento Sustentável',
      sustainableDesc: 'Trabalhando com agricultores e fornecedores confiáveis que seguem práticas sustentáveis',
      locationTitle: 'Localização e Operações',
      locationP1: 'Nossa sede e operações estão baseadas em Malang, Java Oriental, Indonésia. Esta localização estratégica nos proporciona excelente acesso às principais regiões produtoras de coco, bem como conexões logísticas eficientes com portos de embarque internacionais.',
      locationP2: 'Mantemos relacionamentos fortes com fornecedores locais e estabelecemos processos de controle de qualidade em cada etapa—desde a aquisição de matérias-primas até a embalagem e envio final. Nossa equipe experiente garante operações suaves e serviço confiável para todos os nossos parceiros internacionais.',
      ctaTitle: 'Vamos Construir uma Parceria',
      ctaDesc: 'Seja você está procurando um novo fornecedor ou quer diversificar suas fontes, estamos prontos para discutir como podemos atender às suas necessidades.',
      whatsAppUs: 'WhatsApp Conosco',
    },
    whyChooseUs: {
      heroTitle: 'Por Que Nos Escolher',
      heroSubtitle: 'Seu parceiro confiável para derivados de coco de qualidade premium',
      premiumProducts: 'Produtos de Qualidade Premium',
      premiumProductsDesc: 'Cada produto passa por rigoroso controle de qualidade para garantir que atenda aos padrões internacionais de exportação. Trabalhamos apenas com fornecedores de reputação e mantemos processos de inspeção rigorosos desde a aquisição até o envio.',
      stableSupply: 'Fornecimento Estável e Confiável',
      stableSupplyDesc: 'Nossa extensa rede de agricultores, processadores e fornecedores garante disponibilidade consistente durante todo o ano. Entendemos a importância da confiabilidade da cadeia de suprimentos para suas operações comerciais.',
      competitivePricing: 'Preços Competitivos',
      competitivePricingDesc: 'Relacionamentos diretos com fornecedores de origem e operações eficientes nos permitem oferecer preços competitivos sem comprometer a qualidade. Acreditamos em práticas comerciais transparentes e justas.',
      exportReady: 'Cadeia de Suprimentos Pronta para Exportação',
      exportReadyDesc: 'Prontos para apoiar compradores internacionais com tratamento profissional de documentação, logística e requisitos técnicos.',
      professionalService: 'Serviço Profissional',
      professionalServiceDesc: 'Da consulta inicial à entrega, fornecemos serviço profissional e responsivo. Nossa equipe experiente está dedicada a garantir transações suaves e construir parcerias de longo prazo.',
      trustedSourcing: 'Rede de Fornecimento Confiável',
      trustedSourcingDesc: 'Mantemos relacionamentos fortes com agricultores e fornecedores confiáveis que seguem boas práticas agrícolas. Isso garante a qualidade do produto enquanto apoia o fornecimento sustentável.',
      processTitle: 'Nosso Processo de Trabalho',
      processSubtitle: 'Processo simples, transparente e profissional da consulta à entrega',
      step1: 'Consulta e Discussão',
      step1Desc: 'Compartilhe seus requisitos de produto, quantidades e especificações conosco',
      step2: 'Cotação e Amostras',
      step2Desc: 'Receba preços competitivos e amostras de produtos para avaliação, se necessário',
      step3: 'Confirmação do Pedido',
      step3Desc: 'Confirme detalhes do pedido, condições de pagamento e cronograma de entrega',
      step4: 'Controle de Qualidade e Embalagem',
      step4Desc: 'Os produtos são inspecionados, devidamente embalados e preparados para envio',
      step5: 'Envio e Documentação',
      step5Desc: 'Organizamos a logística e fornecemos toda a documentação de exportação necessária',
      step6: 'Suporte Pós-Venda',
      step6Desc: 'Suporte contínuo para sua satisfação e futuras necessidades comerciais',
      ctaTitle: 'Pronto para Experimentar a Diferença?',
      ctaDesc: 'Junte-se à nossa crescente lista de compradores internacionais satisfeitos. Entre em contato conosco hoje para discutir suas necessidades de derivados de coco.',
      chatWhatsApp: 'Chat no WhatsApp',
      sendInquiryNow: 'Enviar Consulta Agora',
    },
    gallery: {
      heroTitle: 'Galeria',
      heroSubtitle: 'Veja nossos produtos, processos de produção e padrões de qualidade',
      category: 'Produtos',
      copraPellet: 'Pellet de Farelo de Copra',
      copraPowder: 'Pó de Farelo de Copra',
      crudeOil: 'Óleo de Coco Bruto',
      exportReadyTitle: 'Cadeia de Suprimentos Pronta para Exportação',
      exportReadyP1: 'Desenvolvemos um sistema integrado de cadeia de suprimentos projetado para apoiar compradores internacionais com clareza, eficiência e profissionalismo. Do controle de qualidade e preparação de documentação de exportação à coordenação logística e comunicação com compradores, cada processo é estruturado para garantir transações suaves e seguras.',
      exportReadyP2: 'Seja você um importador estabelecido ou novo na aquisição de produtos da Indonésia, nossa equipe está pronta para ajudá-lo em cada etapa para garantir que cada pedido atenda às especificações e padrões de qualidade acordados.',
      ctaTitle: 'Interessado em Informações Detalhadas do Produto?',
      ctaDesc: 'Entre em contato conosco para informações detalhadas do produto, especificações ou para solicitar amostras. Estamos aqui para responder a todas as suas perguntas.',
      whatsAppUs: 'WhatsApp Conosco',
    },
    contact: {
      heroTitle: 'Entre em Contato',
      heroSubtitle: 'Vamos discutir como podemos atender às suas necessidades de derivados de coco',
      getInTouch: 'Entre em Contato',
      getInTouchDesc: 'Recebemos consultas de importadores, distribuidores e compradores industriais em todo o mundo. Seja você tem perguntas sobre nossos produtos, precisa de uma cotação ou quer discutir seus requisitos específicos, nossa equipe está pronta para ajudá-lo.',
      address: 'Endereço',
      addressValue: 'Malang, Java Oriental, Indonésia',
      email: 'E-mail',
      whatsApp: 'WhatsApp',
      followUs: 'Siga-nos',
      sendInquiry: 'Enviar Consulta',
      yourName: 'Seu Nome',
      emailAddress: 'Endereço de E-mail',
      companyName: 'Nome da Empresa',
      country: 'País',
      yourMessage: 'Sua Mensagem',
      messagePlaceholder: 'Por favor, forneça detalhes sobre sua consulta, incluindo produto de interesse, quantidades e quaisquer requisitos específicos...',
      sendInquiryNow: 'Enviar Consulta Agora',
      ctaTitle: 'Prefere Conversar Diretamente?',
      ctaDesc: 'Para resposta mais rápida, sinta-se à vontade para entrar em contato conosco diretamente via WhatsApp. Nossa equipe está pronta para responder suas perguntas.',
      chatWhatsApp: 'Chat no WhatsApp',
    },
    footer: {
      tagline: 'Seu Parceiro Fornecedor Confiável em Derivados de Coco Premium',
      quickLinks: 'Links Rápidos',
      contactUs: 'Fale Conosco',
      followUs: 'Siga-nos',
      copyright: 'Todos os direitos reservados.',
    },
  },
};

export default LanguageContext;
